### ISSUE TITLE
SynthesisEngine builds but unable to start

### ISSUE THREAD

**Issue by burgerga** [swoodhouse/SCNS-Toolkit#4]
Crashes with 

```
gerhard@ncase-ubuntu:~/src/SCNS-Toolkit/SynthesisEngine$ bin/Release/SynthesisEngine.exe 
wine: Unhandled page fault on read access to 0x00000000 at address (nil) (thread 0024), starting debugger...
Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x0000000000000000).
```

Anything I can do to figure this out?
[synthesisengine_crash_dump.txt](https://github.com/swoodhouse/SCNS-Toolkit/files/224279/synthesisengine_crash_dump.txt)

**Comment by swoodhouse** [comment]
I haven't tried running SCNS through wine. I would recommend running directly through mono if using Ubuntu.
