### ISSUE TITLE
Question: what are the files `cmp_initial_states.txt` and `cmp_target_states.txt` for?

### ISSUE THREAD

**Issue by burgerga** [swoodhouse/SCNS-Toolkit#5]
I used `constructSTG.fsx` on my gene expression data, but I'm unsure how I should make/generate these other files.

**Comment by swoodhouse** [comment]
SCNS works by looking for a Boolean network that can transition from a set of initial states to a set of target states by making a series of single-gene transitions. These files give the identifiers of the two sets of states.
In the synthetic CMP example, there is a single initial state, and all other states are required to be reachable from it. In the experimental case from our NBT paper, we used cells measured on 'day 1' of our time course experiment as the initial states, and cells measured on the final day as our target states.
