### ISSUE TITLE
Mono version

### ISSUE THREAD

**Issue by skannan4** [swoodhouse/SCNS-Toolkit#7]
To clarify, does constructSTG fail for any version of Mono >4? I initially tried to test on Mono 4.2.1; the error I got when running constructSTG was 'System.IO.FileNotFoundException: Could not find file "/usr/lib/cli/fsharp/testSTG.csv"' where testSTG.csv was my input file. Is this the error referenced in the readme?

Thanks,

Suraj Kannan

**Comment by swoodhouse** [comment]
Hi skannan4, the error here seems to be that fsharpi is trying to look for your csv in its install directory. If you give an absolute path to your file it should work.
