### ISSUE TITLE
How to use the web-based GUI? How to build the network?

### ISSUE THREAD

**Issue by HHHit** [swoodhouse/SCNS-Toolkit#9]
In the paper published on BMC Systems Biology, it is said it provides the web-based GUI, however I cannot find the related information. Can you help me?
Also, how can I build the network using the output txt files? I believe the txt file the shows Boolean relation based on the tree structure, right?

**Comment by HHHit** [comment]
I got it, it is in another repository. Sorry.
The link to the GUI version is at https://github.com/swoodhouse/SCNS-GUI

**Comment by swoodhouse** [comment]
The GUI version can be found here: https://github.com/swoodhouse/SCNS-GUI

**Comment by HHHit** [comment]
Thank you so much!
